name: CI
on:
  # run tests, building, linting, and coverage on pushes to `main` and PRs
  # deployment will happen only for tags, see cd.yml
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write   # needed to push (even with --dry-run) as in the integration suite

jobs:

  # run tests 
  tests:
    name: py${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # add macos-latest, windows-latest if you need
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # default; keeps GITHUB_TOKEN in origin url

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]" # for building, testing, & linting. See setup.cfg

      - name: Lint
        run: |
          pylint version_checker

      - name: Tests
        run: |
          pytest -q --maxfail=1 --disable-warnings
      
      - name: Build
        run: |
          python -m build

      - name: Upload coverage
        if: always()
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          # token: ${{ secrets.CODECOV_TOKEN }}
      
      # FTODO - consider best flow so that folks merging new features are asked to bump in-MR
      # - name: Verify the version was bumped if targeting main
      #   if: github.event_name == 'pull_request' && github.base_ref == 'main'
      #   run: |
      #     git fetch origin main
      #     version_checker -b origin/main -c HEAD

      - name: Verify Integration Tests
        run: |
          # the integration suite tests git hooks, so git creds are necessary (even with --dry-run)
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Ensure remote uses token (belt & suspenders)
          git remote set-url origin \
            https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          # test the hooks / cli
          bash integration-test.sh
